/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as ArtworksArtworkIdIndexRouteImport } from './routes/artworks/$artworkId/index'
import { Route as ArtworksArtworkIdEditRouteImport } from './routes/artworks/$artworkId/edit'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksArtworkIdIndexRoute = ArtworksArtworkIdIndexRouteImport.update({
  id: '/artworks/$artworkId/',
  path: '/artworks/$artworkId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksArtworkIdEditRoute = ArtworksArtworkIdEditRouteImport.update({
  id: '/artworks/$artworkId/edit',
  path: '/artworks/$artworkId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/artworks/$artworkId/edit': typeof ArtworksArtworkIdEditRoute
  '/artworks/$artworkId': typeof ArtworksArtworkIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/artworks/$artworkId/edit': typeof ArtworksArtworkIdEditRoute
  '/artworks/$artworkId': typeof ArtworksArtworkIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/artworks/$artworkId/edit': typeof ArtworksArtworkIdEditRoute
  '/artworks/$artworkId/': typeof ArtworksArtworkIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/cart'
    | '/unauthorized'
    | '/checkout/success'
    | '/artworks/$artworkId/edit'
    | '/artworks/$artworkId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/browse'
    | '/cart'
    | '/unauthorized'
    | '/checkout/success'
    | '/artworks/$artworkId/edit'
    | '/artworks/$artworkId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/cart'
    | '/unauthorized'
    | '/checkout/success'
    | '/artworks/$artworkId/edit'
    | '/artworks/$artworkId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRoute
  BrowseRoute: typeof BrowseRoute
  CartRoute: typeof CartRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ArtworksArtworkIdEditRoute: typeof ArtworksArtworkIdEditRoute
  ArtworksArtworkIdIndexRoute: typeof ArtworksArtworkIdIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks/$artworkId/': {
      id: '/artworks/$artworkId/'
      path: '/artworks/$artworkId'
      fullPath: '/artworks/$artworkId'
      preLoaderRoute: typeof ArtworksArtworkIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks/$artworkId/edit': {
      id: '/artworks/$artworkId/edit'
      path: '/artworks/$artworkId/edit'
      fullPath: '/artworks/$artworkId/edit'
      preLoaderRoute: typeof ArtworksArtworkIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRoute,
  BrowseRoute: BrowseRoute,
  CartRoute: CartRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ArtworksArtworkIdEditRoute: ArtworksArtworkIdEditRoute,
  ArtworksArtworkIdIndexRoute: ArtworksArtworkIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
